import flask

app = flask.Flask(__name__)

# Flood and cholera risk data for each Myanmar state/region.
# Scores are computed using the same scoring engine as the index page (main.js),
# ensuring full data parity between the overview and the live map.
FLOOD_DATA = {
    "Ayeyarwady": {
        "floodRisk": 9,
        "choleraRisk": 8,
        "vaccinePriority": "HIGH",
        "priorityScore": 95,
        "action": "URGENT",
        "population": 6184000,
        "populationAffected": 1546000,
        "chol5yr": 18400,
        "flood5yr": [45, 48, 44, 52, 55],
        "floodProb": 97,
        "currentSupply": 41000,
        "vaccineDosesNeeded": 1546000,
        "vaccineGap": 1505000,
        "coverPct": 3,
        "lastFloodEvent": "2025-06",
        "description": "The Ayeyarwady Delta is one of Myanmar's most flood-prone areas. Annual monsoon flooding affects hundreds of thousands of residents and creates severe cholera outbreak conditions."
    },
    "Rakhine": {
        "floodRisk": 8,
        "choleraRisk": 7,
        "vaccinePriority": "HIGH",
        "priorityScore": 92,
        "action": "URGENT",
        "population": 2098000,
        "populationAffected": 461560,
        "chol5yr": 6200,
        "flood5yr": [35, 32, 38, 42, 45],
        "floodProb": 98,
        "currentSupply": 15000,
        "vaccineDosesNeeded": 461560,
        "vaccineGap": 446560,
        "coverPct": 3,
        "lastFloodEvent": "2025-05",
        "description": "Rakhine State faces dual threats from coastal cyclones and river flooding. Displaced populations in camps have severely limited access to clean water and sanitation."
    },
    "Sagaing": {
        "floodRisk": 8,
        "choleraRisk": 6,
        "vaccinePriority": "HIGH",
        "priorityScore": 83,
        "action": "URGENT",
        "population": 5325000,
        "populationAffected": 1118250,
        "chol5yr": 11400,
        "flood5yr": [28, 31, 26, 35, 38],
        "floodProb": 98,
        "currentSupply": 28000,
        "vaccineDosesNeeded": 1118250,
        "vaccineGap": 1090250,
        "coverPct": 3,
        "lastFloodEvent": "2024-08",
        "description": "Sagaing Region experiences significant Irrawaddy River flooding. Ongoing conflict has disrupted healthcare access, increasing vulnerability to disease outbreaks."
    },
    "Kayin": {
        "floodRisk": 8,
        "choleraRisk": 6,
        "vaccinePriority": "HIGH",
        "priorityScore": 83,
        "action": "URGENT",
        "population": 1574000,
        "populationAffected": 283320,
        "chol5yr": 5200,
        "flood5yr": [22, 25, 20, 28, 30],
        "floodProb": 98,
        "currentSupply": 12000,
        "vaccineDosesNeeded": 283320,
        "vaccineGap": 271320,
        "coverPct": 4,
        "lastFloodEvent": "2024-09",
        "description": "Kayin State experiences significant flooding along the Salween and Gyaing rivers every monsoon season, with rural communities most affected."
    },
    "Bago": {
        "floodRisk": 9,
        "choleraRisk": 6,
        "vaccinePriority": "HIGH",
        "priorityScore": 87,
        "action": "URGENT",
        "population": 4867000,
        "populationAffected": 924730,
        "chol5yr": 9800,
        "flood5yr": [30, 28, 36, 34, 37],
        "floodProb": 98,
        "currentSupply": 38000,
        "vaccineDosesNeeded": 924730,
        "vaccineGap": 886730,
        "coverPct": 4,
        "lastFloodEvent": "2024-09",
        "description": "Bago Region experiences severe flooding along the Bago and Sittaung rivers every monsoon season, with significant displacement and waterborne disease risk."
    },
    "Mon": {
        "floodRisk": 9,
        "choleraRisk": 6,
        "vaccinePriority": "HIGH",
        "priorityScore": 87,
        "action": "URGENT",
        "population": 2054000,
        "populationAffected": 410800,
        "chol5yr": 7600,
        "flood5yr": [32, 35, 30, 38, 40],
        "floodProb": 98,
        "currentSupply": 18000,
        "vaccineDosesNeeded": 410800,
        "vaccineGap": 392800,
        "coverPct": 4,
        "lastFloodEvent": "2024-09",
        "description": "Mon State's coastal lowlands and river networks flood extensively during monsoon season, disrupting water supplies and elevating cholera risk."
    },
    "Yangon": {
        "floodRisk": 8,
        "choleraRisk": 6,
        "vaccinePriority": "HIGH",
        "priorityScore": 86,
        "action": "URGENT",
        "population": 7360000,
        "populationAffected": 956800,
        "chol5yr": 7200,
        "flood5yr": [22, 20, 26, 24, 27],
        "floodProb": 72,
        "currentSupply": 88000,
        "vaccineDosesNeeded": 956800,
        "vaccineGap": 868800,
        "coverPct": 9,
        "lastFloodEvent": "2024-09",
        "description": "As Myanmar's largest city, Yangon's dense population and ageing drainage infrastructure make it highly vulnerable. Urban flooding leads to significant cholera exposure risk."
    },
    "Tanintharyi": {
        "floodRisk": 8,
        "choleraRisk": 6,
        "vaccinePriority": "HIGH",
        "priorityScore": 80,
        "action": "URGENT",
        "population": 1408000,
        "populationAffected": 239360,
        "chol5yr": 4100,
        "flood5yr": [24, 22, 28, 30, 32],
        "floodProb": 98,
        "currentSupply": 11000,
        "vaccineDosesNeeded": 239360,
        "vaccineGap": 228360,
        "coverPct": 5,
        "lastFloodEvent": "2024-09",
        "description": "Tanintharyi Region's long coastline and numerous river systems experience heavy flooding during monsoon season, affecting coastal communities significantly."
    },
    "Nay Pyi Taw": {
        "floodRisk": 6,
        "choleraRisk": 6,
        "vaccinePriority": "HIGH",
        "priorityScore": 74,
        "action": "URGENT",
        "population": 1160000,
        "populationAffected": 92800,
        "chol5yr": 900,
        "flood5yr": [5, 4, 6, 5, 6],
        "floodProb": 41,
        "currentSupply": 14000,
        "vaccineDosesNeeded": 92800,
        "vaccineGap": 78800,
        "coverPct": 15,
        "lastFloodEvent": "2023-09",
        "description": "The capital union territory has better infrastructure reducing flood impact, though some rural townships remain vulnerable during heavy monsoon rains."
    },
    "Mandalay": {
        "floodRisk": 7,
        "choleraRisk": 6,
        "vaccinePriority": "HIGH",
        "priorityScore": 78,
        "action": "URGENT",
        "population": 6165000,
        "populationAffected": 739800,
        "chol5yr": 8900,
        "flood5yr": [18, 16, 22, 19, 22],
        "floodProb": 67,
        "currentSupply": 52000,
        "vaccineDosesNeeded": 739800,
        "vaccineGap": 687800,
        "coverPct": 7,
        "lastFloodEvent": "2024-08",
        "description": "Mandalay faces moderate flooding risk from the Irrawaddy River. Urban water supply disruption during floods elevates cholera risk in densely populated areas."
    },
    "Magway": {
        "floodRisk": 6,
        "choleraRisk": 6,
        "vaccinePriority": "HIGH",
        "priorityScore": 76,
        "action": "URGENT",
        "population": 3913000,
        "populationAffected": 430430,
        "chol5yr": 4400,
        "flood5yr": [12, 11, 15, 14, 15],
        "floodProb": 67,
        "currentSupply": 34000,
        "vaccineDosesNeeded": 430430,
        "vaccineGap": 396430,
        "coverPct": 8,
        "lastFloodEvent": "2024-08",
        "description": "Magway Region's dry zone experiences less severe flooding, but flash floods in low-lying areas still pose risks to rural communities."
    },
    "Shan": {
        "floodRisk": 6,
        "choleraRisk": 5,
        "vaccinePriority": "HIGH",
        "priorityScore": 67,
        "action": "URGENT",
        "population": 5820000,
        "populationAffected": 756600,
        "chol5yr": 6800,
        "flood5yr": [20, 18, 25, 23, 26],
        "floodProb": 66,
        "currentSupply": 31000,
        "vaccineDosesNeeded": 756600,
        "vaccineGap": 725600,
        "coverPct": 4,
        "lastFloodEvent": "2024-07",
        "description": "Shan State's high plateau limits widespread flooding, though river valleys and lower-lying areas experience seasonal flash floods."
    },
    "Kachin": {
        "floodRisk": 5,
        "choleraRisk": 5,
        "vaccinePriority": "MEDIUM",
        "priorityScore": 63,
        "action": "PREPARE",
        "population": 1689000,
        "populationAffected": 236460,
        "chol5yr": 3200,
        "flood5yr": [11, 9, 14, 12, 14],
        "floodProb": 63,
        "currentSupply": 9800,
        "vaccineDosesNeeded": 236460,
        "vaccineGap": 226660,
        "coverPct": 4,
        "lastFloodEvent": "2024-07",
        "description": "Kachin State's mountainous terrain leads to flash flooding events in river valleys. Internally displaced people face elevated health risks."
    },
    "Kayah": {
        "floodRisk": 4,
        "choleraRisk": 6,
        "vaccinePriority": "MEDIUM",
        "priorityScore": 63,
        "action": "PREPARE",
        "population": 286000,
        "populationAffected": 20020,
        "chol5yr": 310,
        "flood5yr": [3, 2, 4, 3, 4],
        "floodProb": 41,
        "currentSupply": 2800,
        "vaccineDosesNeeded": 20020,
        "vaccineGap": 17220,
        "coverPct": 14,
        "lastFloodEvent": "2023-08",
        "description": "Kayah State has a relatively lower flood risk due to its elevated terrain, though localised flooding does occur in some townships."
    },
    "Chin": {
        "floodRisk": 4,
        "choleraRisk": 5,
        "vaccinePriority": "MEDIUM",
        "priorityScore": 61,
        "action": "PREPARE",
        "population": 478000,
        "populationAffected": 38240,
        "chol5yr": 420,
        "flood5yr": [2, 4, 3, 5, 5],
        "floodProb": 41,
        "currentSupply": 4200,
        "vaccineDosesNeeded": 38240,
        "vaccineGap": 34040,
        "coverPct": 11,
        "lastFloodEvent": "2023-08",
        "description": "Chin State's mountainous geography leads primarily to landslide risk rather than widespread flooding. Cholera risk remains low compared to delta regions."
    }
}

@app.route('/')
def index():
    return flask.render_template('index.html')

@app.route('/map')
def map_page():
    return flask.render_template('map.html')

@app.route('/api/flood-data')
def flood_data():
    return flask.jsonify(FLOOD_DATA)

if __name__ == '__main__':
    app.run(debug=True)
